# Generated by Django 4.2 on 2023-10-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_gender_name_alter_parent_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='class_student_set', through='main.ClassStudent', to='main.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(related_name='class_subject_set', through='main.ClassSubject', to='main.subject'),
        ),
        migrations.AlterModelTable(
            name='gender',
            table='gender',
        ),
        migrations.AlterModelTable(
            name='profession',
            table='profession',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
    ]
