# Generated by Django 4.2 on 2023-11-02 07:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_staff_options_alter_class_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_of_create', models.DateTimeField(auto_now_add=True)),
                ('date_of_update', models.DateTimeField(auto_now=True)),
                ('management_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('responsibility', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.MinLengthValidator(7)])),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.gender')),
            ],
            options={
                'db_table': 'management',
            },
        ),
    ]
